import monstera from "../assets/monstera.jpg";

export const plantList = [
  {
    id: "1ab",
    name: "monstera",
    category: "intérieur",
    cover: monstera,
    light: 2,
    water: 1,
    price: 15,
    quantity: 8,
  },
  {
    id: "2cd",
    name: "ficus lyrata",
    category: "extérieur",
    cover: monstera,
    light: 3,
    water: 2,
    price: 16,
    quantity: 9,
  },
  {
    id: "3ef",
    name: "pothos argenté",
    category: "intérieur",
    cover: monstera,
    light: 3,
    water: 3,
    price: 9,
    quantity: 5,
  },
  {
    id: "4gh",
    name: "yucca",
    category: "grimpante",
    cover: monstera,
    light: 1,
    water: 2,
    price: 12,
    quantity: 6,
  },
  {
    id: "5ij",
    name: "palmier",
    category: "extérieur",
    cover: monstera,
    light: 3,
    water: 1,
    price: 19,
    quantity: 3,
  },
];
